apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: darklang-tls-ingress
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  backend:
    serviceName: darklang-nodeport
    servicePort: 80
  tls:
    - secretName: darklang-tls
