version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      TAG: 500377317163.dkr.ecr.us-east-1.amazonaws.com/dark-ci:latest2
      RUST_TAG: 500377317163.dkr.ecr.us-east-1.amazonaws.com/dark-ci:rust-latest2
    steps:
      - checkout
      - setup_remote_docker: { docker_layer_caching: true }
      # Save the docker env: type .docker-env when sshing in, then you can
      # use ./scripts/run-in-docker
      - run:
          name: Setup docker-env for debugging
          command: env | grep 'DOCKER\|NO_PROXY' | sed 's/^/export /' > ../docker-env

      - run: apk add --update bash python3 --update-cache
      - run: pip3 install awscli --upgrade --user
      - run: docker build --target dark-base -t $TAG .
      - run: docker build -t $RUST_TAG .
      - deploy:
          name: Push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              $(/root/.local/bin/aws ecr get-login --no-include-email --region us-east-1)
              docker push $TAG
              docker push $RUST_TAG
            fi


