version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      TAG: darklang/dark-base
      RUST_TAG: darklang/dark-rust
    steps:
      - checkout
      - setup_remote_docker: { docker_layer_caching: true }
      # Save the docker env: type .docker-env when sshing in, then you can
      # use ./scripts/run-in-docker
      - run:
          name: Setup docker-env for debugging
          command: env | grep 'DOCKER\|NO_PROXY' | sed 's/^/export /' > ../docker-env

      - run: echo "Building images for version $(./tag-version.sh)."
      - run: docker build --target dark-base -t $TAG:$(./tag-version.sh) .
      - run: docker build -t $RUST_TAG:rust-$(./tag-version.sh) .
      - deploy:
          name: Push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login --username pbiggar --password "${DOCKER_HUB_TOKEN}"
              docker push $TAG:$(./tag-version.sh)
              docker push $RUST_TAG:rust-$(./tag-version.sh)
            fi


